version: '3'
services:
  sms:
    build:
     context: .
     dockerfile: package/docker/Dockerfile
    environment:
      ORIGINATOR: ${ORIGINATOR}
      TOKEN: ${TOKEN}
    ports:
      - "8001:8080"
