sms:
  originator: Bahmni
  clientId: MOK3WVSPLJIC128rjvvOAQ8Six0zZRgPaUrnRLc0
  clientSecret: VAF63B9r9cjn3CQI7S3j0NBrTcB21WEWFgywa2t24BjAVntLmXjanaBr1Pt450v5Sma4lGpjMWZ1wcBQVIvP8BBwt4gRRgUBAmb1XDfFDl0PagL9Ak6mdEeGdPaTRLt1